version: 2
jobs:
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: yarn-install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - run:
          name: release
          command: yarn release
workflows:
  version: 2
  build_and_release:
    jobs:
      - release:
          filters:
            branches:
              only: master
